### ISSUE TITLE
Brick and NetherBrick stairs don't connect properly

### ISSUE THREAD

**Issue by enizor** [fiftywalrus/SmoothOperator#1]
- The icons for the (nether) brick stairs are not 3D 
![2017-06-11_23 46 17](https://user-images.githubusercontent.com/25256520/27014813-7c2aad50-4f00-11e7-808d-012acba3609e.png)
 - They do not connect properly when upside down (other stairs for comparison): 
![2017-06-11_23 45 21](https://user-images.githubusercontent.com/25256520/27014819-988675d8-4f00-11e7-9c49-d579abab7f14.png)
![2017-06-11_23 45 32](https://user-images.githubusercontent.com/25256520/27014820-99f25162-4f00-11e7-8731-6cf5bada6c02.png)
![2017-06-11_23 45 40](https://user-images.githubusercontent.com/25256520/27014821-9b329ae6-4f00-11e7-9749-96cdd3b9894e.png)
![2017-06-11_23 46 03](https://user-images.githubusercontent.com/25256520/27014822-9c4a68c8-4f00-11e7-8067-5d2a26bd462c.png)

**Comment by fiftywalrus** [comment]
thanks for reporting this! Yes it was a mistake in the json files for the stair blockstate and model/item files.  I have just fixed them and they are submitted now
![2017-06-19_20 34 27](https://user-images.githubusercontent.com/11017383/27300074-c3d2d72a-552e-11e7-9b65-8b155b8162dc.png)
