### ISSUE TITLE
Fire Texture showing missing texture

### ISSUE THREAD

**Issue by Sci648** [fiftywalrus/SmoothOperator#3]
Noticed that the fire texture was not working for some reason. 
- noticed when mobs caught fire they displayed fire no problem
- Tested other textures packs. they had no problem
- Tested with default minecraft and optifine C4 and the issue persisted.
- Noticed one other person posted an issue on curse.

Thought I would post here with a couple of screen shots to hopefully help you out if you have not already found the issue.
![2017-07-30_18 36 32](https://user-images.githubusercontent.com/29790869/28758157-06c8646a-7559-11e7-9d96-eac0ca920e34.png)

![2017-07-30_18 43 46](https://user-images.githubusercontent.com/29790869/28758159-0dcb08d0-7559-11e7-91d6-6cb98fd0a91e.png)

**Comment by fiftywalrus** [comment]
Fixed
