### ISSUE TITLE
There is no attack cool down indicator

### ISSUE THREAD

**Issue by IAmV0id** [fiftywalrus/SmoothOperator#4]
I have set it to true on the optifine settings, yet they aren't appearing. How ever without the resource pack I am able to see it. Can you go fix this annoying issue please?

**Comment by SCP002** [comment]
To fix (kind of) this issue for myself, I created small resource pack which contain only gui icons from faithful x32. 
Just add resource pack in attachment above the smooth operator. It will override other icons styling from smooth operator, but still, IMO, it looks good.
[GUI_Icons_Faithful.zip](https://github.com/fiftywalrus/SmoothOperator/files/3464827/GUI_Icons_Faithful.zip)

**Comment by fiftywalrus** [comment]
Ah yes I missed that one. It's in the new texture now and submitted.
